name: Fetch FYTV M3U

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"  # every 24 hours

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create target directory
        run: mkdir -p rawaddress

      - name: Download M3U file
        run: |
          curl -L \
            "http://iptv.4666888.xyz/FYTV.m3u" \
            -o rawaddress/FYTV.m3u

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add rawaddress/FYTV.m3u

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "Update feiyang.m3u"
          git push
