name: Update and Fix zb.txt to merged.m3u

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests chardet

      - name: Fetch and fix zb.txt
        run: |
          python - <<'EOF'
          import requests, chardet, os

          url = "http://47.120.41.246:8899/zb.txt"
          r = requests.get(url, timeout=20)
          raw = r.content

          # Detect encoding
          det = chardet.detect(raw)
          enc = det['encoding'] or 'ISO-8859-1'
          try:
              text = raw.decode(enc)
          except:
              text = raw.decode('ISO-8859-1')

          # Try to repair UTF-8 double encoding
          try:
              fixed = text.encode('latin1').decode('utf-8')
          except:
              fixed = text

          # Convert to M3U format
          lines = [l.strip() for l in fixed.splitlines() if l.strip()]
          m3u = ["#EXTM3U"]
          for line in lines:
              if "," in line and not line.startswith("#"):
                  name, url = line.split(",", 1)
                  m3u.append(f"#EXTINF:-1,{name.strip()}")
                  m3u.append(url.strip())

          with open("merged.m3u", "w", encoding="utf-8") as f:
              f.write("\n".join(m3u))

          print("✅ Created merged.m3u successfully.")
          EOF

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain merged.m3u)" ]]; then
            git add merged.m3u
            git commit -m "Update merged.m3u from zb.txt"
            git push
          else
            echo "No changes to commit."
          fi
